name: Release Docker Images
on:
  push:
    branches:
      - main
    paths:
      - "python/tokenspeed/version.py"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.repository == 'lightseekorg/tokenspeed'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runner_tag: ['cu130-torch-2.11.0', 'cu129-torch-2.11.0']
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: false

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: |
          docker build . \
            -f docker/Dockerfile \
            --build-arg RUNNER_TAG=${{ matrix.runner_tag }} \
            -t lightseekorg/tokenspeed:${{ matrix.runner_tag }} \
            --no-cache
